/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StaffRegisterRouteImport } from './routes/staff-register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffsRouteImport } from './routes/_authenticated/staffs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSelectRoleRouteImport } from './routes/_authenticated/select-role'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyServicesRouteImport } from './routes/_authenticated/my-services'
import { Route as AuthenticatedMyProductsRouteImport } from './routes/_authenticated/my-products'
import { Route as AuthenticatedMyOrdersRouteImport } from './routes/_authenticated/my-orders'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfileIdRouteImport } from './routes/_authenticated/profile.$id'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin.disputes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRegisterRoute = StaffRegisterRouteImport.update({
  id: '/staff-register',
  path: '/staff-register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffsRoute = AuthenticatedStaffsRouteImport.update({
  id: '/staffs',
  path: '/staffs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectRoleRoute = AuthenticatedSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyServicesRoute = AuthenticatedMyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProductsRoute = AuthenticatedMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyOrdersRoute = AuthenticatedMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileIdRoute = AuthenticatedProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProfileRoute,
} as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/admin/disputes',
    path: '/admin/disputes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/staff-register': typeof StaffRegisterRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/my-services': typeof AuthenticatedMyServicesRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staffs': typeof AuthenticatedStaffsRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/staff-register': typeof StaffRegisterRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/my-services': typeof AuthenticatedMyServicesRoute
  '/select-role': typeof AuthenticatedSelectRoleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staffs': typeof AuthenticatedStaffsRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/profile/$id': typeof AuthenticatedProfileIdRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/staff-register': typeof StaffRegisterRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/_authenticated/my-orders': typeof AuthenticatedMyOrdersRoute
  '/_authenticated/my-products': typeof AuthenticatedMyProductsRoute
  '/_authenticated/my-services': typeof AuthenticatedMyServicesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/select-role': typeof AuthenticatedSelectRoleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staffs': typeof AuthenticatedStaffsRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/profile/$id': typeof AuthenticatedProfileIdRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/staff-register'
    | '/terms'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/messages'
    | '/my-bookings'
    | '/my-orders'
    | '/my-products'
    | '/my-services'
    | '/profile'
    | '/select-role'
    | '/settings'
    | '/staffs'
    | '/admin/disputes'
    | '/profile/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/staff-register'
    | '/terms'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/messages'
    | '/my-bookings'
    | '/my-orders'
    | '/my-products'
    | '/my-services'
    | '/select-role'
    | '/settings'
    | '/staffs'
    | '/admin/disputes'
    | '/profile/$id'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/privacy'
    | '/staff-register'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/messages'
    | '/_authenticated/my-bookings'
    | '/_authenticated/my-orders'
    | '/_authenticated/my-products'
    | '/_authenticated/my-services'
    | '/_authenticated/profile'
    | '/_authenticated/select-role'
    | '/_authenticated/settings'
    | '/_authenticated/staffs'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/profile/$id'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  StaffRegisterRoute: typeof StaffRegisterRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-register': {
      id: '/staff-register'
      path: '/staff-register'
      fullPath: '/staff-register'
      preLoaderRoute: typeof StaffRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staffs': {
      id: '/_authenticated/staffs'
      path: '/staffs'
      fullPath: '/staffs'
      preLoaderRoute: typeof AuthenticatedStaffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-role': {
      id: '/_authenticated/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof AuthenticatedSelectRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-services': {
      id: '/_authenticated/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof AuthenticatedMyServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products': {
      id: '/_authenticated/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof AuthenticatedMyProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-orders': {
      id: '/_authenticated/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/$id': {
      id: '/_authenticated/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AuthenticatedProfileIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileIdRoute: typeof AuthenticatedProfileIdRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileIdRoute: AuthenticatedProfileIdRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedMyOrdersRoute: typeof AuthenticatedMyOrdersRoute
  AuthenticatedMyProductsRoute: typeof AuthenticatedMyProductsRoute
  AuthenticatedMyServicesRoute: typeof AuthenticatedMyServicesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedSelectRoleRoute: typeof AuthenticatedSelectRoleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffsRoute: typeof AuthenticatedStaffsRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedMyOrdersRoute: AuthenticatedMyOrdersRoute,
  AuthenticatedMyProductsRoute: AuthenticatedMyProductsRoute,
  AuthenticatedMyServicesRoute: AuthenticatedMyServicesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedSelectRoleRoute: AuthenticatedSelectRoleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffsRoute: AuthenticatedStaffsRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  StaffRegisterRoute: StaffRegisterRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
